HydroCloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'account'

urlpatterns = [
    path('', TemplateView.as_view(template_name='landing.html'), name='landing'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('check_code/', views.code, name='code'),
    path('profile/', views.profile, name='profile'),
    path('create_image/', views.create_image, name='create_image'),
    path('all_results/', views.get_all_results, name='all_results'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static "img/favicon.ico" %}">
    <title>HydroCloud{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extrahead %}{% endblock %}
</head>
<body>
<header>
    <div class="logo" onclick="window.location='{% url 'account:landing' %}'">
        <img src="{% static 'img/logo.png' %}" alt="logo">
    </div>
    {% if user.is_authenticated %}
        <div class="sign_btns">
            <a href="{% url 'account:create_image' %}" class="sign_btns-btn">Generate image</a>
            <a class="sign_btns-btn" href="{% url 'account:logout' %}">Log out</a>
        </div>
    {% else %}
        <div class="sign" onclick="window.location='{% url 'account:user_login' %}'">
        <div class="sign-img">
            <img src="{% static 'img/sign_in.png' %}" alt="SignIn Icon">
        </div>
        <div class="sign-text">
            Войти
        </div>
    {% endif %}
    </div>
</header>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/landing.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
{% endblock %}

{% block content %}
    <div class="landing">
        <div class="hero">
            <div class="hero-text">
                Сервис для построения гидроакустических изображений
            </div>
            <div class="hero_btns">
                {% if user.is_authenticated %}
                    <button class="hero_btns-btn btn" onclick="window.location='{% url 'account:profile' %}'">Открыть профиль</button>
                {% else %}
                    <button class="hero_btns-btn btn" onclick="window.location='{% url 'account:register' %}'">Зарегистрироваться</button>
                {% endif %}
                <button class="hero_btns-btn btn" onclick="window.location='{% url 'account:all_results' %}'">Просмотреть результаты</button>
            </div>
        </div>
        <div class="algs">
            <div class="algs-title title">Алгоритмы</div>
            <div class="algs_cards">
                <div class="algs_cards_card">
                    <div class="algs_cards_card-title">Медианная фильтрация</div>
                    <div class="algs_cards_card-description">
                        Медианная фильтрация — эффективная процедура обработки сигналов, подверженных воздействию импульсных помех.
                        Этот метод направлен на фильтрацию высоко- и низкоамплитудных шумов
                    </div>
                </div>
                <div class="algs_cards_card">
                    <div class="algs_cards_card-title">Алгоритм фильтрации объёмного рассеяния</div>
                    <div class="algs_cards_card-description">
                        Объемное рассеяние звука в толще вод океана происходит на флуктуациях показателя преломления звуковых волн
                        (гидрологические неоднородности) и на дискретных инородных включениях, которыми в первую очередь являются живые
                        организмы. Для количественного описания объемного рассеяния в обратном направлении служит коэффициент,
                        характеризующий рассеяние единицы объема среды и имеющий, в отличие от коэффициента рассеяния на неровной границе,
                        размерность 1/м
                    </div>
                </div>
                <div class="algs_cards_card">
                    <div class="algs_cards_card-title">Двойная фильтрация</div>
                    <div class="algs_cards_card-description">
                        Двойная фильтрация справляется с удалением низкоамплитудных и импульсных шумов, наиболее выгодна для сильно
                        зашумленных изображений
                    </div>
                </div>
                <div class="algs_cards_card">
                    <div class="algs_cards_card-title">Логарифмическая фильтрация</div>
                    <div class="algs_cards_card-description">
                        Логарифмическая фильтрация решает проблему появления в изображении белого шума
                    </div>
                </div>
            </div>
        </div>
        <div class="command">
            <div class="command-title title">Команда</div>
            <div class="command_cards">
                <div class="command_cards_card">
                    <div class="command_cards_card-img">
                        <img src="{% static 'img/logo.png' %}" alt="Profile image">
                    </div>
                    <div class="command_cards_card_body">
                        <div class="command_cards_card_body-title">Сущенко Андрей Андреевич</div>
                        <div class="command_cards_card_body-info">
                            Руководитель образовательной программы
                        </div>
                    </div>
                </div>
                <div class="command_cards_card">
                    <div class="command_cards_card-img">
                        <img src="{% static 'img/logo.png' %}" alt="Profile image">
                    </div>
                    <div class="command_cards_card_body">
                        <div class="command_cards_card_body-title">Ярушина Мария Григорьевна</div>
                        <div class="command_cards_card_body-info">
                            4 курс направления: “Прикладная Математика и Информатика”. Б9118-01.03.02систро
                        </div>
                    </div>
                </div>
                <div class="command_cards_card">
                    <div class="command_cards_card-img">
                        <img src="{% static 'img/logo.png' %}" alt="Profile image">
                    </div>
                    <div class="command_cards_card_body">
                        <div class="command_cards_card_body-title">Салушкин Дмитрий Сергеевич</div>
                        <div class="command_cards_card_body-info">
                            4 курс направления: “Прикладная Математика и Информатика”. Б9118-01.03.миопд
                        </div>
                    </div>
                </div>
                <div class="command_cards_card">
                    <div class="command_cards_card-img">
                        <img src="{% static 'img/logo.png' %}" alt="Profile image">
                    </div>
                    <div class="command_cards_card_body">
                        <div class="command_cards_card_body-title">Синькова Маргарита Евгеньевна</div>
                        <div class="command_cards_card_body-info">
                            4 курс направления: “Прикладная Математика и Информатика”. Б9118-01.03.миопд
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}